          <h4 style="color: red;">Warning, 99% of these settings aren't working !</h4>
          <a href="//exaload.glitch.me/settings"><h3>Compte</h3></a>
          <a href="//exaload.glitch.me/settings/appearance"><h3>Apparence</h3></a>
          <a href="//exaload.glitch.me/settings/backgrounds"><h3>Fonds d'écran</h3></a>
          <a href="//exaload.glitch.me/settings/special-effects"><h3>Effets Spéciaux</h3></a>
          <a href="//exaload.glitch.me/settings/games"><h3>Jeux</h3></a>
          <a href="//exaload.glitch.me/settings/films"><h3>Films</h3></a>
          <a href="//exaload.glitch.me/settings/series"><h3>Séries</h3></a>
          <a href="//exaload.glitch.me/settings/musics"><h3>Musiques</h3></a>
          <a href="//exaload.glitch.me/settings/apps"><h3>Applications</h3></a>
          <a href="//exaload.glitch.me/political-things"><h3>Affaires politiques</h3></a>